import { FontAwesomeIcon } from '@fortawesome/react-fontawesome' /* font awesome */
import { faStar as regularStar } from '@fortawesome/free-solid-svg-icons'/* font awesome */
import { faStar as solidStar } from '@fortawesome/free-regular-svg-icons'/* font awesome */
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import 'bootstrap-icons/font/bootstrap-icons.css'
import axios from 'axios'
import { useState } from 'react'
import AppHeader from './components/AppHeader'
import MovieCards from './components/MovieCards'
import SeriesCards from './components/SeriesCards'
import './App.css'

function App() {
  /* obj of nation to let react-country-flag work */
  const languages = {
    it: "IT",
    en: "GB",
    us: "US",
    fr: "FR",
    ja: "JP",
    de: "DE",
    /* the other one from here are generated by AI help to make it faster */
    es: "ES",
    pt: "PT",
    nl: "NL",
    pl: "PL",
    ru: "RU",
    tr: "TR",
    br: "BR",
    ca: "CA",
    mx: "MX",
    zh: "CN",
    ko: "KR",
    hi: "IN",
    ar: "SA",
    vi: "VN",
    th: "TH",
    au: "AU",
    za: "ZA",
    eg: "EG",
    ng: "NG"
  }
  /* function to change flags with react country flag */
  const countryFlag = language => languages[language] || "UN"
  /* useState for the input search */
  const [search, setSearch] = useState("")
  /* useState for store API Movies data */
  const [movies, setMovies] = useState([])
  /* useState for store API Tv data */
  const [tvSeries, setTvSeries] = useState([])

  const handleSearch = () => {
    Promise.all([
      axios.get(movieUrl),  /* fetch for movies */
      axios.get(tvSeriesUrl) /* fetch for tv series */
    ])
      .then(([movieRes, seriesRes]) => {
        setMovies(movieRes.data.results);
        setTvSeries(seriesRes.data.results);
      })
  }
  /* function for render stars/votes */
  const renderStar = (voteAverage) => {
    const rating = Math.ceil(voteAverage / 2);
    const result = [];
    for (let i = 1; i <= 5; i++) {
      result.push(
        <FontAwesomeIcon
          key={i}
          icon={i <= rating ? regularStar : solidStar}
          className='text-warning '
        />
      );
    }
    return result;
  };
  const api_key = import.meta.env.VITE_API_KEY
  const movieUrl = `https://api.themoviedb.org/3/search/movie?api_key=${api_key}&query=${search}` /* movies */
  const tvSeriesUrl = `https://api.themoviedb.org/3/search/tv?api_key=${api_key}&query=${search}` /* tv series */
  const posters = `https://image.tmdb.org/t/p/w500/` /* create a variable with initial url for poster */
  return (
    <>
      <AppHeader search={search} handleSearch={handleSearch} setSearch={(e) => setSearch(e.target.value)} ></AppHeader>
      <div className="container">

        <MovieCards movies={movies} countryFlag={countryFlag} renderStar={renderStar} posters={posters}></MovieCards>

        <SeriesCards tvSeries={tvSeries} countryFlag={countryFlag} renderStar={renderStar} posters={posters}></SeriesCards> 
      </div>
    </>
  )
}

export default App
