import ReactCountryFlag from 'react-country-flag' /* import ReactCountryFlag to make the flag change dynamically */
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import 'bootstrap-icons/font/bootstrap-icons.css'
import axios from 'axios'
import { useState } from 'react'

function App() {

  /* obj of nation to let react-country-flag work */
  const languages = {
    it: "IT",
    en: "GB",
    us: "US",
    fr: "FR",
    ja: "JP",
    de: "DE",
    /* the other one from here are generated by AI help to make it faster */
    es: "ES",
    pt: "PT",
    nl: "NL",
    pl: "PL",
    ru: "RU",
    tr: "TR",
    br: "BR",
    ca: "CA",
    mx: "MX",
    zh: "CN",
    ko: "KR",
    hi: "IN",
    ar: "SA",
    vi: "VN",
    th: "TH",
    au: "AU",
    za: "ZA",
    eg: "EG",
    ng: "NG"
  }

  /* function to change flags with react country flag */
  const countryFlag = language => languages[language] || "UN"

  /* useState for the input search */
  const [search, setSearch] = useState("")
  /* useState for store API Movies data */
  const [movies, setMovies] = useState([])
  /* useState for store API Tv data */
  const [tvSeries, setTvSeries] = useState([])

  const handleSearch = () => {
    Promise.all([
      axios.get(movieUrl),  /* fetch for movies */
      axios.get(tvSeriesUrl) /* fetch for tv series */
    ])
      .then(([movieRes, seriesRes]) => {
        setMovies(movieRes.data.results);
        setTvSeries(seriesRes.data.results);
      })
  }

  const api_key = import.meta.env.VITE_API_KEY
  const movieUrl = `https://api.themoviedb.org/3/search/movie?api_key=${api_key}&query=${search}` /* movies */
  const tvSeriesUrl = `https://api.themoviedb.org/3/search/tv?api_key=${api_key}&query=${search}` /* tv series */
  const posters = `https://image.tmdb.org/t/p/w500/` /* create a variable with initial url */

  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col">
            {/* input camp where i can get by onChange user writing with setSearch and target value */}
            <input type="text" value={search} onChange={(e) => setSearch(e.target.value)}></input>
            {/* button to trigger the handleSearch for get the API call */}
            <button onClick={handleSearch} >Cerca</button>

          </div>
        </div>
        {/* make a new row to map the handleSearch */}
        <div className="row">
          {/* map movies */}
          {movies.map(movie => (
            /* use the value we need to render from the movies map */
            <ul key={movie.id}>
              <li>{movie.title}</li>
              <li>{movie.original_title}</li>
              <li> <ReactCountryFlag
                countryCode={countryFlag(movie.original_language)}
                svg
                title={movie.original_language.toUpperCase()}
              />{' '}
                {movie.original_language.toUpperCase()}</li>
              <li>{movie.vote_average}</li>
              <li><img src ={`${posters}${movie.poster_path}`} alt="wewe" /></li> {/* join url with the fetch img */}
            </ul>
          ))}
          {/* map movies end */}
        </div>

        <div className="row">
          {/* map series */}
          {tvSeries.map(series => (
            <ul key={series.id}>
              <li>{series.name}</li>
              <li>{series.original_name}</li>
              <li> <ReactCountryFlag
                countryCode={countryFlag(series.original_language)}
                svg
                title={series.original_language.toUpperCase()}
              />{' '}
                {series.original_language.toUpperCase()}</li>
              <li>{series.vote_average}</li>
              <li><img src ={`${posters}${series.poster_path}`} alt="wewe" /></li> {/* join url with the fetch img */}
            </ul>
          ))}
          {/* map series end */}
        </div>
      </div>
    </>
  )
}

export default App
